### ISSUE TITLE
SECRET_KEY_BASE in Dockerfile

### ISSUE THREAD

**Issue by sdarwin** [opensanca/opensanca_jobs#163]
Build the docker image in production:

`docker build --build-arg build_without="development test" --build-arg rails_env="production" .`

It crashes with the following error:

ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`

A solution is suggested in https://github.com/rails/rails/issues/32947

"Using workaround `` SECRET_KEY_BASE=`bin/rake secret` bin/rake assets:precompile `` for now."

Probably that should be added to the Dockerfile ?

**Comment by duduribeiro** [comment]
Hey @sdarwin 👋 

thanks for opening the issue. I fixed it on https://github.com/opensanca/opensanca_jobs/commit/66d1d9ab36fb2903ea0299317257f7ed296700b0

can you test?

I only added a dumb default environment variable to not cause this problem. When running in some environment, this can be replaced.

thanks 🍻

**Comment by sdarwin** [comment]
> can you test?

I believe that fixed it. Great!  Can be closed.  Continuing to test, in general...
