### ISSUE TITLE
Post jobs to opensanca's Linkedin

### ISSUE THREAD

**Issue by marquesds** [opensanca/opensanca_jobs#51]
Using Linkedin's API, automagically post jobs to opensanca's Linkedin: https://www.linkedin.com/company-beta/10968431/

**Comment by duduribeiro** [comment]
The problem is, the Job position is not from Opensanca. I think that we should post it in the company's linkedin page. What you think @marquesds ?

**Comment by marquesds** [comment]
You are right. But I think it'll be nice if we share these jobs in at least one social network (maybe Facebook).

**Comment by duduribeiro** [comment]
I think that we can go on Facebook and Twitter

**Comment by marquesds** [comment]
Great. I'll close this issue and create another. Thanks!
