### ISSUE TITLE
Restrict access to sidekiq web dashboard

### ISSUE THREAD

**Issue by emeraquino** [opensanca/opensanca_jobs#80]
Currently the sidekiq web dashboard is publicly accessible: http://openjobs.me/sidekiq

Maybe put it behind Google OAuth?
REF: https://github.com/mperham/sidekiq/wiki/Monitoring#rails-with-google-authentication

**Comment by duduribeiro** [comment]
Yeah. We definitely should do this.

But I think we should do a Http basic authentication instead of a google authentication.
